version: "3.7"
services:
  db:
    image: postgres
    container_name: "beauty-clinic-system-db"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
      - "./src/main/resources/db/changelog/init.sql:/docker-entrypoint-initdb.d/1-init.sql"
    environment:
      - POSTGRES_DB=beauty-clinic-system-api
      - POSTGRES_USER=maju
      - POSTGRES_PASSWORD=maju
      - TZ=GMT
    ports:
      - "5433:5433"
    restart: always
networks:
  app-network:
    driver: bridge
